# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{letsfreckle-client}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan LeCompte"]
  s.date = %q{2011-07-25}
  s.description = %q{Ruby client for letsfreckle.com API that supports entries, projects, tags, and users}
  s.email = %q{lecompte@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "letsfreckle-client.gemspec",
    "lib/letsfreckle.rb",
    "lib/letsfreckle/client_resource.rb",
    "lib/letsfreckle/configuration.rb",
    "lib/letsfreckle/entry.rb",
    "lib/letsfreckle/error.rb",
    "lib/letsfreckle/extensions/mash.rb",
    "lib/letsfreckle/project.rb",
    "lib/letsfreckle/tag.rb",
    "lib/letsfreckle/user.rb",
    "spec/letsfreckle/configuration_spec.rb",
    "spec/letsfreckle/entry_spec.rb",
    "spec/letsfreckle/project_spec.rb",
    "spec/letsfreckle/tag_spec.rb",
    "spec/letsfreckle/user_spec.rb",
    "spec/responses/entries.xml.response",
    "spec/responses/projects.xml.response",
    "spec/responses/tags.xml.response",
    "spec/responses/users.xml.response",
    "spec/spec_helper.rb",
    "spec/support/webmock_helper.rb"
  ]
  s.homepage = %q{http://github.com/ryanlecompte/letsfreckle-client}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby client for letsfreckle.com API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.6.2"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<webmock>, ["~> 1.6.2"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<webmock>, ["~> 1.6.2"])
  end
end

